theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "aider"
  - scope:
      path: "examples"
      type: "pages"
    values:
      description: "aider is GPT-4 powered coding in your terminal"
