theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "examples"
      type: "pages"
    values:
      description: "examples desc"
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "home desc"
      
