theme: jekyll-theme-cayman
url: "https://aider.chat"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "A command-line chat tool for coding with GPT"

exclude:
  - tmp.benchmarks
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - other_directories_or_files_to_exclude
