theme: jekyll-theme-cayman
url: "https://aider.chat"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "A command-line chat tool for coding with GPT"

exclude:
  - tmp.benchmarks
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - other_directories_or_files_to_exclude
CNAME
CONTRIBUTING.md
Dockerfile~
Gemfile
Gemfile.lock
HISTORY.md
HISTORY.md~
LICENSE.txt
MANIFEST.in
OLD
README.md
__pycache__
_config.yml
_config.yml~
_data
_layouts
_posts
_site
aider
aider_chat.egg-info
assets
badedit.md~
benchmark
blog
branches_to_delete.txt~
bug.md~
bug2.md~
build
current.txt~
desired.txt~
dev-requirements.in
dev-requirements.in~
dev-requirements.txt
docker
docs
examples
indent.md~
no-dots-edit.md~
pytest.ini
pytest.ini~
raggit.py~
requirements.in
requirements.in~
requirements.txt
rqh.py~
scripts
setup.py
share
tests
tmp
tmp.0125.graphs.sh
tmp.0125.graphs.sh~
tmp.CONTRIBUTING.md
tmp.README.md
tmp.after
tmp.after2
tmp.after~
tmp.all
tmp.all-lazy-exercises
tmp.all-lazy-exercises~
tmp.all-lazy-files
tmp.all-lazy-files.new
tmp.all-lazy-files.new.top17
tmp.applied
tmp.before
tmp.before~
tmp.benchmarks
tmp.claude3.graphs.sh
tmp.claude3.graphs.sh~
tmp.convo
tmp.convo~
tmp.diff
tmp.diff~
tmp.du
tmp.edit.json
tmp.edit.md
tmp.edit.md~
tmp.elides
tmp.err
tmp.foo.py
tmp.gast.storage
tmp.gemini.29eb2f4
tmp.gemini.cleaned-up
tmp.gitlog
tmp.gpt-4-turbo-2024-04-09.graphs.sh
tmp.gpt-4-turbo-2024-04-09.graphs.sh~
tmp.history
tmp.html
tmp.in
tmp.issue.html
tmp.issue.html~
tmp.issue.md
tmp.issue.txt
tmp.jpg
tmp.json
tmp.kernel.py
tmp.last-edit.md
tmp.llama.storage-git
tmp.map
tmp.md
tmp.new
tmp.noop.yml
tmp.noop.yml~
tmp.number.json
tmp.number.json~
tmp.old
tmp.out
tmp.paasio
tmp.pdf
tmp.png
tmp.pricing.md
tmp.prof
tmp.py
tmp.py~
tmp.refactor
tmp.replace-lines
tmp.response
tmp.search_replace_diff.html
tmp.sed
tmp.server.py
tmp.sh
tmp.share.md
tmp.share.md~
tmp.sh~
tmp.sitemap.xml
tmp.skill.sh
tmp.skill.sh~
tmp.slim.html
tmp.space space.txt
tmp.speed.sh
tmp.speed.sh~
tmp.st.py
tmp.st.py~
tmp.subdir
tmp.summary
tmp.svg
tmp.sync.sh
tmp.sync.sh~
tmp.timing
tmp.ts-pr.md
tmp.ts-pr.md~
tmp.txt
tmp.udiff.graphs.sh
tmp.udiff.graphs.sh~
tmp.udiff.sh
tmp.udiff.sh~
tmp.unterminated.json
tmp.windows.txt
tmp.windows.txt~
tmp.xxx
tmp_timing.svg
