theme: jekyll-theme-cayman
url: "https://aider.chat"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      description: "A command-line chat tool for coding with GPT"

exclude:
  - tmp.benchmarks
  - .git
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
