REPO_URLS: https://github.com/rkalahasty/terraformtest1
REPO_TYPE: mono
REPO_BRANCH: forge
# Authentication
GIT_TOKEN: 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
# Local Settings
LOCAL_CLONE_PATH: test_repos
GOOGLE_API_KEY: AIzaSyAd23JkHP6I-eRA0HTU0oiVfOv6IOpXpgk

# Rohan's Key
OPENAI_API_KEY: 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

PINECONE_API_KEY: pcsk_6R9y8j_98K3wtDe6J7CLMQNcyPr77jzZnVDgeeH82cmFGhUsrmWW4V2cC2pnzTFjUiNk8w
