name: Question or bug repot
description: Submit a question or bug report to help us improve aider
labels: []
body:
  - type: textarea
    attributes:
      label: Issue
      description: Please describe your problem or question.
    validations:
      required: true      
  - type: markdown
    attributes:
      value: |
        When asking questions or reporting issues, it is very helpful if you can include:

        - Aider version
        - Model being used (`gpt-4-xxx`, etc)
        - Other switches or config settings that are active

        The easiest way to do this is just just copy & paste the announcement lines that aider prints when you launch it, like these:

        ```
        Aider v0.21.2-dev
        Model: gpt-4-0613 using diff edit format
        Git repo: .git with 134 files
        Repo-map: using 1024 tokens
        Use /help to see in-chat commands, run with --help to see cmd line args
        ```        
  - type: textarea
    attributes:
      label: Version and model info
      description: Please include the aider version, model name and other config/switches in effect.
    validations:
      required: false