name: Question or bug report
description: Submit a question or bug report to help us improve aider
labels: []
body:
  - type: textarea
    attributes:
      label: Issue
      description: Please describe your problem or question.
    validations:
      required: true      
  - type: textarea
    attributes:
      label: Version and model info
      description: Please include the aider version, model name and other config/switches in effect.
      placeholder: |
        Please include aider version, model being used (`gpt-4-xxx`, etc) and any other switches or config settings that are active. Just copy & paste these lines from aider's output:
          
        Aider v0.21.2-dev
        Model: gpt-4-0613 using diff edit format
        Git repo: .git with 134 files
        Repo-map: using 1024 tokens
    validations:
      required: false