terraform:
  api_url: "https://registry.terraform.io/v2"
  auth_token: ""  # Optional: Add your token for higher rate limits
  providers:
    - aws
    - google
    - azurerm
    - kubernetes
    - docker
    - helm
    - null
    - random
    - time
    - local
  documentation_sources:
    - type: registry
      url: "https://registry.terraform.io"
      priority: 1
    - type: github
      url: "https://raw.githubusercontent.com/hashicorp"
      priority: 2
    - type: official
      url: "https://developer.hashicorp.com/terraform"
      priority: 1
    - type: community
      url: "https://github.com/terraform-aws-modules"
      priority: 3
  update_interval: 86400  # 24 hours
  similarity_thresholds:
    min_score: 0.3
    high_confidence: 0.7
    provider_specific: 0.5
  content_filters:
    min_length: 50
    max_length: 10000
    required_fields:
      - title
      - description
    optional_fields:
      - examples
      - arguments
      - attributes

kubernetes:
  api_url: "https://kubernetes.default.svc"
  update_interval: 3600

docker:
  api_url: "unix:///var/run/docker.sock"
  update_interval: 3600

gitlab:
  api_url: "https://gitlab.com/api/v4"
  update_interval: 3600

github:
  api_url: "https://api.github.com"
  update_interval: 3600

jenkins:
  api_url: "http://jenkins:8080"
  update_interval: 3600

ansible:
  doc_path: "/usr/share/ansible/doc"
  update_interval: 3600

prometheus:
  api_url: "http://prometheus:9090/api/v1"
  update_interval: 3600

grafana:
  api_url: "http://grafana:3000/api"
  update_interval: 3600
